backend:
  name: github
  repo: BiZHR/cannabizhr_website
  branch: main
  auth_scope: repo
  base_url: https://bizhr.org
  auth_endpoint: /api/auth

publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
